describe('empty spec', () => {
  it('passes', () => {
    cy.visit('http://127.0.0.1:8000/login')
    cy.get('#email').type('hilmy@gmail.com')
    cy.get('#password').type('hilmy123')
    cy.get('#sign-in > .ps-form__content > .submtit > .ps-btn').click()
    cy.get('.header__content-right > .header__actions > .ps-block--user-header > .ps-block__right > a').click()
    cy.get('.ps-widget__content > ul > :nth-child(8) > a').click()
    cy.get('.ps-widget__content > ul > :nth-child(7) > a').click()
    cy.get(':nth-child(1) > .form-group > .form-control').clear().type('Barokah Jaya')
    cy.get(':nth-child(2) > .form-group > .form-control').clear().type('Jalan Soekarno - Hatta')
    cy.get('.col-sm-12 > .form-group > .form-control').clear().type('Toko ini menjual berbagai macam bahan bangunan')
    cy.get(':nth-child(4) > .form-group > .form-control').select(11)
    cy.get(':nth-child(5) > .form-group > .form-control').select(18)
    cy.get(':nth-child(6) > .form-group > .form-control').select(4)
    cy.get('.form-control-file').selectFile('cypress/e2e/toko.jpg')
    cy.get('.submit > .ps-btn').click()
  })
})
